from django.core.management.base import BaseCommand
from catalogo.models import FamiliaProducto, Proyecto


FAMILIAS_DATA = [
    {
        'nombre': 'TIRAS LED ARQ',
        'macro': 'Tiras LED',
        'tipo': 'Tiras LED',
        'descripcion': 'Luz continua, sin puntos ni interrupciones, para integrarse en cualquier detalle arquitectónico. Tecnología SMD de alta densidad con control DALI, 1-10V y TRIAC, pensada para los proyectos donde la precisión lumínica define el resultado final.',
        'skus': 22,
        'photo': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K', '3000K', '4000K', 'CCT/Dinámico'],
        'filter_ip': ['IP20', 'IP33', 'IP65'],
        'filter_dim_sys': ['1-10V', 'DALI', 'DMX', 'TRIAC'],
        'filter_cri': ['CRI≥80', 'CRI≥90', 'CRI≥95'],
        'filter_v': ['24V'],
        'filter_w': ['<10 W', '10-20 W', '20-40 W'],
        'filter_ubicacion': ['Interior', 'Exterior'],
        'filter_aplicacion': ['Pared', 'Techo'],
        'filter_montaje': ['Aplicado', 'Embutido'],
        'has_dim': True,
        'w_range': [4.8, 34.0],
        'orden': 1,
    },
    {
        'nombre': 'TIRAS LED HOGAR',
        'macro': 'Tiras LED',
        'tipo': 'Tiras LED',
        'descripcion': 'La calidez de un hogar bien iluminado, sin resignar calidad. Tiras LED pensadas para aplicaciones residenciales con instalación sencilla y resultado profesional.',
        'skus': 8,
        'photo': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K', '4000K', 'CCT/Dinámico'],
        'filter_ip': ['IP20'],
        'filter_dim_sys': [],
        'filter_cri': ['CRI≥80'],
        'filter_v': ['12V'],
        'filter_w': ['<10 W', '10-20 W'],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Pared', 'Techo', 'Mueble'],
        'filter_montaje': ['Aplicado'],
        'has_dim': False,
        'w_range': [4.4, 19.2],
        'orden': 2,
    },
    {
        'nombre': 'PERFILES PORTALED',
        'macro': 'Tiras LED',
        'tipo': 'Tiras LED',
        'descripcion': 'El marco perfecto para la luz. Perfiles de aluminio anodizado que protegen, disipan el calor y terminan la instalación con el acabado que merece.',
        'skus': 10,
        'photo': 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=800&auto=format&fit=crop&q=80',
        'filter_ct': [],
        'filter_ip': [],
        'filter_dim_sys': [],
        'filter_cri': [],
        'filter_v': [],
        'filter_w': [],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Pared', 'Techo', 'Mueble'],
        'filter_montaje': ['Embutido', 'Aplicado'],
        'has_dim': False,
        'w_range': [],
        'orden': 3,
    },
    {
        'nombre': 'JENNY',
        'macro': 'Empotrados',
        'tipo': 'Empotrados',
        'descripcion': 'Una miniatura con presencia. Módulo empotrable de tamaño reducido y óptica de alta calidad, con CRI superior a 90 para una reproducción de color fiel y precisa.',
        'skus': 36,
        'photo': 'https://www.wlgled.com.ar/wp-content/uploads/2025/12/cover_jennyxpro.prueba-1.jpg',
        'filter_ct': ['2700K', '3000K', '4000K', 'CCT/Dinámico'],
        'filter_ip': ['IP65'],
        'filter_dim_sys': ['DALI', 'DMX', 'TRIAC'],
        'filter_cri': ['CRI≥80', 'CRI≥90'],
        'filter_v': ['24V', '48V'],
        'filter_w': ['<10 W', '10-20 W', '20-40 W'],
        'filter_ubicacion': ['Interior', 'Exterior'],
        'filter_aplicacion': ['Techo', 'Pared'],
        'filter_montaje': ['Embutido'],
        'has_dim': True,
        'w_range': [5.0, 20.0],
        'orden': 4,
    },
    {
        'nombre': 'FUENTES',
        'macro': 'Accesorios',
        'tipo': 'Accesorios',
        'descripcion': 'El corazón silencioso de cada instalación. Fuentes switching de 12V y 24V con opciones de regulación integrada, certificadas y diseñadas para instalaciones exigentes.',
        'skus': 26,
        'photo': 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?w=800&auto=format&fit=crop&q=80',
        'filter_ct': [],
        'filter_ip': ['IP20'],
        'filter_dim_sys': ['1-10V', 'DALI', 'TRIAC'],
        'filter_cri': [],
        'filter_v': ['12V', '24V', '48V'],
        'filter_w': [],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': [],
        'filter_montaje': [],
        'has_dim': False,
        'w_range': [],
        'orden': 5,
    },
    {
        'nombre': 'LÁMPARAS',
        'macro': 'Artefactos',
        'tipo': 'Artefactos',
        'descripcion': 'Reemplazo directo, resultado inmediato. Lámparas LED E27 y GU10 regulables, con CRI superior a 90 y temperatura de color precisa para cada ambiente.',
        'skus': 13,
        'photo': 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K', '3000K'],
        'filter_ip': ['IP20'],
        'filter_dim_sys': ['TRIAC'],
        'filter_cri': ['CRI≥80', 'CRI≥90', 'CRI≥95'],
        'filter_v': ['220V', '36V'],
        'filter_w': ['<10 W', '10-20 W'],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Mesa', 'Techo'],
        'filter_montaje': ['Aplicado'],
        'has_dim': True,
        'w_range': [5.0, 15.0],
        'orden': 6,
    },
    {
        'nombre': 'ARTEFACTOS GU/AR',
        'macro': 'Artefactos',
        'tipo': 'Artefactos',
        'descripcion': 'El soporte justo para la lámpara correcta. Artefactos de superficie e inclinados para lámparas GU10 y AR111, con acabados de calidad arquitectónica.',
        'skus': 6,
        'photo': 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&auto=format&fit=crop&q=80',
        'filter_ct': [],
        'filter_ip': ['IP20'],
        'filter_dim_sys': [],
        'filter_cri': [],
        'filter_v': ['220V'],
        'filter_w': [],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Techo', 'Pared'],
        'filter_montaje': ['Aplicado'],
        'has_dim': False,
        'w_range': [],
        'orden': 7,
    },
    {
        'nombre': 'KATAN',
        'macro': 'Empotrados',
        'tipo': 'Empotrados',
        'descripcion': 'Pequeño tamaño, gran impacto. Empotrado circular compacto con protección IP44, orientable 35° y ópticas de precisión para puntos de luz perfectamente dirigidos.',
        'skus': 6,
        'photo': 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K'],
        'filter_ip': ['IP44'],
        'filter_dim_sys': ['TRIAC'],
        'filter_cri': ['CRI≥80', 'CRI≥90', 'CRI≥95'],
        'filter_v': ['220V'],
        'filter_w': ['<10 W'],
        'filter_ubicacion': ['Interior', 'Exterior'],
        'filter_aplicacion': ['Techo', 'Piso'],
        'filter_montaje': ['Embutido'],
        'has_dim': True,
        'w_range': [3.0, 5.0],
        'orden': 8,
    },
    {
        'nombre': 'MICRO RUNNER',
        'macro': 'Rieles',
        'tipo': 'Rieles',
        'descripcion': 'Precisión óptica en el mínimo espacio posible. Proyector empotrable de tamaño reducido para sistemas de riel, con beam angles ajustables y CRI superior a 90.',
        'skus': 17,
        'photo': 'https://www.wlgled.com.ar/wp-content/uploads/2025/12/cover_micro_runner7.prueba.jpg',
        'filter_ct': ['2700K', '3000K'],
        'filter_ip': ['IP20'],
        'filter_dim_sys': ['DALI', 'TRIAC'],
        'filter_cri': ['CRI≥80', 'CRI≥90', 'CRI≥95'],
        'filter_v': ['220V'],
        'filter_w': ['<10 W', '10-20 W'],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Techo'],
        'filter_montaje': ['Embutido'],
        'has_dim': True,
        'w_range': [2.0, 20.0],
        'orden': 9,
    },
    {
        'nombre': 'RUNNER X PRO',
        'macro': 'Rieles',
        'tipo': 'Rieles',
        'descripcion': 'Rendimiento profesional sin concesiones. Runner de alta potencia y CRI superior a 90 con control DALI, diseñado para proyectos donde la calidad de luz define la experiencia.',
        'skus': 17,
        'photo': 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K', '3000K'],
        'filter_ip': ['IP20'],
        'filter_dim_sys': ['DALI', 'TRIAC'],
        'filter_cri': ['CRI≥80', 'CRI≥90', 'CRI≥95'],
        'filter_v': ['220V'],
        'filter_w': ['<10 W', '10-20 W', '20-40 W'],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Techo'],
        'filter_montaje': ['Suspendido', 'Aplicado'],
        'has_dim': True,
        'w_range': [2.0, 30.0],
        'orden': 10,
    },
    {
        'nombre': 'TRACK LV',
        'macro': 'Rieles',
        'tipo': 'Rieles',
        'descripcion': 'Luz que acompaña el recorrido. Sistema de riel de 48V de bajo voltaje, con flexibilidad de diseño y seguridad extra en instalaciones accesibles.',
        'skus': 7,
        'photo': 'https://www.wlgled.com.ar/wp-content/uploads/2025/12/tracklights_cover.prueba.jpg',
        'filter_ct': [],
        'filter_ip': ['IP20'],
        'filter_dim_sys': [],
        'filter_cri': [],
        'filter_v': ['48V'],
        'filter_w': [],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Techo'],
        'filter_montaje': ['Suspendido', 'Aplicado'],
        'has_dim': False,
        'w_range': [],
        'orden': 11,
    },
    {
        'nombre': 'TRACKLIGHTS',
        'macro': 'Rieles',
        'tipo': 'Rieles',
        'descripcion': 'Versatilidad sobre cada riel. Proyectores con control DALI, 1-10V y ON/OFF, pensados para comercios, galerías y espacios donde orientar la luz es parte del diseño.',
        'skus': 31,
        'photo': 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K', '3000K', '4000K'],
        'filter_ip': ['IP20'],
        'filter_dim_sys': ['1-10V', 'DALI', 'TRIAC'],
        'filter_cri': ['CRI≥80', 'CRI≥90', 'CRI≥95'],
        'filter_v': ['220V', '48V'],
        'filter_w': ['<10 W', '10-20 W', '20-40 W'],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Techo'],
        'filter_montaje': ['Suspendido', 'Aplicado'],
        'has_dim': True,
        'w_range': [3.0, 27.0],
        'orden': 12,
    },
    {
        'nombre': 'MÓDULOS LED',
        'macro': 'Empotrados',
        'tipo': 'Empotrados',
        'descripcion': 'El componente invisible que hace toda la diferencia. Módulos LED de alto CRI, diseñados para integrarse en sistemas de iluminación empotrada con máxima eficiencia lumínica.',
        'skus': 13,
        'photo': 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K', '3000K', '4000K'],
        'filter_ip': [],
        'filter_dim_sys': [],
        'filter_cri': ['CRI≥80', 'CRI≥90'],
        'filter_v': ['220V'],
        'filter_w': ['<10 W', '10-20 W', '20-40 W', '>40 W'],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Techo', 'Pared'],
        'filter_montaje': ['Embutido'],
        'has_dim': False,
        'w_range': [],
        'orden': 13,
    },
    {
        'nombre': 'WALLY',
        'macro': 'Apliques',
        'tipo': 'Apliques',
        'descripcion': 'Una línea de luz que dibuja el espacio. Aplique de pared lineal, arquitectónico y slim, con distribución asimétrica para bañar superficies con precisión.',
        'skus': 14,
        'photo': 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K', '3000K'],
        'filter_ip': ['IP20'],
        'filter_dim_sys': ['DALI', 'TRIAC'],
        'filter_cri': ['CRI≥80', 'CRI≥90'],
        'filter_v': ['220V'],
        'filter_w': ['20-40 W', '>40 W'],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Pared'],
        'filter_montaje': ['Aplicado'],
        'has_dim': True,
        'w_range': [20.0, 58.0],
        'orden': 14,
    },
    {
        'nombre': 'LINEAR',
        'macro': 'Apliques',
        'tipo': 'Apliques',
        'descripcion': 'Luz rasante que revela texturas. Bañador lineal de pared, slim y compatible con DALI, diseñado para destacar planos verticales con una distribución precisa y homogénea.',
        'skus': 14,
        'photo': 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K', '3000K'],
        'filter_ip': ['IP20'],
        'filter_dim_sys': ['DALI', 'TRIAC'],
        'filter_cri': ['CRI≥80', 'CRI≥90'],
        'filter_v': ['220V'],
        'filter_w': ['10-20 W', '20-40 W', '>40 W'],
        'filter_ubicacion': ['Interior'],
        'filter_aplicacion': ['Pared'],
        'filter_montaje': ['Aplicado'],
        'has_dim': True,
        'w_range': [15.0, 60.0],
        'orden': 15,
    },
    {
        'nombre': 'EXTERIOR',
        'macro': 'Exterior',
        'tipo': 'Exterior',
        'descripcion': 'El jardín, de noche, también es arquitectura. Iluminación exterior con protección IP65, diseñada para integrarse al paisaje y resistir la intemperie sin perder presencia.',
        'skus': 12,
        'photo': 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=800&auto=format&fit=crop&q=80',
        'filter_ct': ['2700K', '3000K', '4000K'],
        'filter_ip': ['IP65'],
        'filter_dim_sys': ['TRIAC'],
        'filter_cri': ['CRI≥80'],
        'filter_v': ['220V'],
        'filter_w': ['<10 W', '10-20 W', '20-40 W', '>40 W'],
        'filter_ubicacion': ['Exterior'],
        'filter_aplicacion': ['Piso', 'Pared'],
        'filter_montaje': ['Aplicado', 'Embutido'],
        'has_dim': True,
        'w_range': [3.0, 50.0],
        'orden': 16,
    },
    {
        'nombre': 'SISTEMAS CONTROL',
        'macro': 'Accesorios',
        'tipo': 'Accesorios',
        'descripcion': 'El cerebro detrás de cada escena lumínica. Controladores TRIAC, DALI, DMX, Casambi y WiFi para gestionar instalaciones simples o complejas con total precisión.',
        'skus': 10,
        'photo': 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&auto=format&fit=crop&q=80',
        'filter_ct': [],
        'filter_ip': ['IP20', 'IP44'],
        'filter_dim_sys': ['1-10V', 'Casambi', 'DALI', 'DMX', 'TRIAC', 'WiFi'],
        'filter_cri': [],
        'filter_v': ['220V', '24V'],
        'filter_w': [],
        'filter_ubicacion': ['Interior', 'Exterior'],
        'filter_aplicacion': [],
        'filter_montaje': [],
        'has_dim': False,
        'w_range': [],
        'orden': 17,
    },
]


class Command(BaseCommand):
    help = 'Carga datos iniciales de familias de productos y proyectos'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Cargando datos iniciales...'))

        for data in FAMILIAS_DATA:
            familia, created = FamiliaProducto.objects.get_or_create(
                nombre=data['nombre'],
                defaults={
                    'macro': data['macro'],
                    'tipo': data['tipo'],
                    'descripcion': data['descripcion'],
                    'skus': data['skus'],
                    'photo': data['photo'],
                    'filter_ct': data['filter_ct'],
                    'filter_ip': data['filter_ip'],
                    'filter_dim_sys': data['filter_dim_sys'],
                    'filter_cri': data['filter_cri'],
                    'filter_v': data['filter_v'],
                    'filter_w': data['filter_w'],
                    'filter_ubicacion': data['filter_ubicacion'],
                    'filter_aplicacion': data['filter_aplicacion'],
                    'filter_montaje': data['filter_montaje'],
                    'has_dim': data['has_dim'],
                    'w_range': data['w_range'],
                    'orden': data['orden'],
                }
            )
            if not created:
                # Update filter fields on existing records
                for field in ['macro', 'tipo', 'descripcion', 'skus', 'photo',
                              'filter_ct', 'filter_ip', 'filter_dim_sys', 'filter_cri',
                              'filter_v', 'filter_w', 'filter_ubicacion', 'filter_aplicacion',
                              'filter_montaje', 'has_dim', 'w_range', 'orden']:
                    setattr(familia, field, data[field])
                familia.save()
                self.stdout.write(f'↺ Familia actualizada: {familia.nombre}')
            else:
                self.stdout.write(f'✓ Familia creada: {familia.nombre}')

        # Proyectos
        proyectos_data = [
            {
                'nombre': 'La Rural',
                'ubicacion': 'Buenos Aires',
                'año': 2024,
                'tipo_espacio': 'Galerías',
                'descripcion': 'Proyecto de iluminación arquitectónica para galerías de arte',
            },
            {
                'nombre': 'Movistar Arena VIP',
                'ubicacion': 'Buenos Aires',
                'año': 2024,
                'tipo_espacio': 'Entretenimiento',
                'descripcion': 'Iluminación premium para espacios VIP en arena de eventos',
            },
            {
                'nombre': 'Torre Bella',
                'ubicacion': 'Palermo, CABA',
                'año': 2023,
                'tipo_espacio': 'Residencial',
                'descripcion': 'Iluminación arquitectónica para torre residencial de lujo',
            },
            {
                'nombre': 'Parfumerie Recoleta',
                'ubicacion': 'Recoleta, CABA',
                'año': 2023,
                'tipo_espacio': 'Retail',
                'descripcion': 'Iluminación especializada para tienda de perfumería premium',
            },
            {
                'nombre': 'La Rando',
                'ubicacion': 'San Telmo, CABA',
                'año': 2022,
                'tipo_espacio': 'Gastronomía',
                'descripcion': 'Iluminación ambiental para restaurante de diseño',
            },
        ]

        for proyecto_data in proyectos_data:
            proyecto, created = Proyecto.objects.get_or_create(
                nombre=proyecto_data['nombre'],
                defaults={
                    'ubicacion': proyecto_data['ubicacion'],
                    'año': proyecto_data['año'],
                    'tipo_espacio': proyecto_data['tipo_espacio'],
                    'descripcion': proyecto_data['descripcion'],
                    'imagen_principal': 'proyectos/placeholder.jpg',
                }
            )
            if created:
                self.stdout.write(f'✓ Proyecto creado: {proyecto.nombre}')
            else:
                self.stdout.write(f'- Proyecto ya existe: {proyecto.nombre}')

        self.stdout.write(self.style.SUCCESS('\n✓ Datos iniciales cargados correctamente'))
